### ISSUE TITLE
"Error: [20011] Invalid input data." in http.get/post when the length of a response header value >= 4084 but the client curl command ok!

### ISSUE THREAD

**Issue by forchid** [fibjs/fibjs#769]
Recently the problem of fibjs http client makes me confused when I am developing an application by using huawei cloud api `https://iam.myhuaweicloud.com/v3/auth/tokens` that has a long response header ["X-Subject-Token"](https://support.huaweicloud.com/api-iam/iam_30_0001.html#section5). 

# Version information
Fibjs v0.36.0, windows 10 x64.

# The standalone test case
```javascript
// http-long-header-test.js
const http = require('http');

var server = new http.Server(8088, req => {
  let rep = req.response;
  let hlen = req.query.get('header-length');
  let longHeader = '';
  
  if (hlen == null) hlen = 1024;
  else hlen = parseInt(hlen);
  for (let i = 0; i < hlen; ++i) {
    longHeader += 'a';
  }
  console.log('%s: header-length = %s(%s)', req.method, hlen, typeof(hlen));
  rep.setHeader('Long-Header', longHeader);
  rep.json({"header-length": hlen });
});
server.start();

// Do test
var rep = http.get('http://localhost:8088/');
rep = http.post('http://localhost:8088/?header-length=0');
rep = http.get('http://localhost:8088/?header-length=10');
rep = http.post('http://localhost:8088/?header-length=100');
rep = http.get('http://localhost:8088/?header-length=1000');
rep = http.post('http://localhost:8088/?header-length=1024');
rep = http.get('http://localhost:8088/?header-length=4083');
// "Error: [20011] Invalid input data." thrown when the length of header value > 4083!!
var len = 4084, i = len, times = 16;
for (; i < len + times; ++i) {
  try {
    if ((i % 2) == 0) {
      rep = http.get('http://localhost:8088/?header-length='+ i);
    } else {
      rep = http.post('http://localhost:8088/?header-length='+ i);
    }
    break;
  } catch (e) {
    console.error(e);
  }
}
if (i >= len + times) {
  console.error("Fatal!!");
  process.exit(1);
} else {
  console.log("OK.");
  process.exit(0);
}
```

# The fibjs http client test case result
```shell
D:\code\fibjs\test>fibjs http-long-header-test.js
GET: header-length = 1024(number)
POST: header-length = 0(number)
GET: header-length = 10(number)
POST: header-length = 100(number)
GET: header-length = 1000(number)
POST: header-length = 1024(number)
GET: header-length = 4083(number)
GET: header-length = 4084(number)
GET: header-length = 4084(number)
Error: [20011] Invalid input data.
    at D:\code\fibjs\test\http-long-header-test.js:33:18
POST: header-length = 4085(number)
Error: [20011] Invalid input data.
    at D:\code\fibjs\test\http-long-header-test.js:35:18
GET: header-length = 4086(number)
Error: [20011] Invalid input data.
    at D:\code\fibjs\test\http-long-header-test.js:33:18
POST: header-length = 4087(number)
Error: [20011] Invalid input data.
    at D:\code\fibjs\test\http-long-header-test.js:35:18
GET: header-length = 4088(number)
Error: [20011] Invalid input data.
    at D:\code\fibjs\test\http-long-header-test.js:33:18
POST: header-length = 4089(number)
Error: [20011] Invalid input data.
    at D:\code\fibjs\test\http-long-header-test.js:35:18
GET: header-length = 4090(number)
Error: [20011] Invalid input data.
    at D:\code\fibjs\test\http-long-header-test.js:33:18
POST: header-length = 4091(number)
Error: [20011] Invalid input data.
    at D:\code\fibjs\test\http-long-header-test.js:35:18
GET: header-length = 4092(number)
Error: [20011] Invalid input data.
    at D:\code\fibjs\test\http-long-header-test.js:33:18
POST: header-length = 4093(number)
Error: [20011] Invalid input data.
    at D:\code\fibjs\test\http-long-header-test.js:35:18
GET: header-length = 4094(number)
Error: [20011] Invalid input data.
    at D:\code\fibjs\test\http-long-header-test.js:33:18
POST: header-length = 4095(number)
Error: [20011] Invalid input data.
    at D:\code\fibjs\test\http-long-header-test.js:35:18
GET: header-length = 4096(number)
Error: [20011] Invalid input data.
    at D:\code\fibjs\test\http-long-header-test.js:33:18
POST: header-length = 4097(number)
Error: [20011] Invalid input data.
    at D:\code\fibjs\test\http-long-header-test.js:35:18
GET: header-length = 4098(number)
Error: [20011] Invalid input data.
    at D:\code\fibjs\test\http-long-header-test.js:33:18
POST: header-length = 4099(number)
Error: [20011] Invalid input data.
    at D:\code\fibjs\test\http-long-header-test.js:35:18
Fatal!!
```

# The http client curl command test result
```shell
C:\Users\Administrator>curl -v http://localhost:8088/?header-length=4084
*   Trying ::1...
* TCP_NODELAY set
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8088 (#0)
> GET /?header-length=4084 HTTP/1.1
> Host: localhost:8088
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Long-Header: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
.....
aaaaaaaaaaaaaaaaaaa
< Content-Type: application/json
< Server: fibjs/0.36.0
< Cache-Control: no-cache, no-store
< Expires: -1
< Connection: keep-alive
< Content-Length: 22
<
{"header-length":4084}* Connection #0 to host localhost left intact

C:\Users\Administrator>curl -v http://localhost:8088/?header-length=4085
*   Trying ::1...
* TCP_NODELAY set
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8088 (#0)
> GET /?header-length=4085 HTTP/1.1
> Host: localhost:8088
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Long-Header: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
.....
aaaaaaaaaaaaaaaaaaaa
< Content-Type: application/json
< Server: fibjs/0.36.0
< Cache-Control: no-cache, no-store
< Expires: -1
< Connection: keep-alive
< Content-Length: 22
<
{"header-length":4085}* Connection #0 to host localhost left intact

C:\Users\Administrator>
```

**Comment by xicilion** [comment]
add maxHeaderLength to fix it:
https://github.com/fibjs/fibjs/commit/bbb0b594c0edebab07b75d01beede9ec129aa425

**Comment by xicilion** [comment]
Renamed to maxHeaderSize for nodejs compatibility.

**Comment by forchid** [comment]
> Renamed to maxHeaderSize for nodejs compatibility.

OK. Thanks!
